language: node_js
node_js:
  - "8"
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - cargo install wasm-gc
cache:
  cargo: true
  directories:
    - node_modules