[package]
name = "fiveo-wasm-target"
version = "0.2.1"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]

[dependencies]
fiveo = "0.2.0"

[features]
profiling = []

[lib]
path = "./src/bindings/ffi/lib.rs"
crate-type = ["cdylib"]

[profile.release]
debug = true
